### ISSUE TITLE
Separate room into their own .hx file & other snippets of code in general like player

### ISSUE THREAD

**Issue by amykatname** [amykatname/newhorizons#4]
To summarize: THIS IS SPAGHETTI CODE lol

**Comment by marvhus** [comment]
I would say that this is complete, as player code is now in `penguin/Penguin.hx` and input related code for the player is in `penguin/PenguinController.hx`.

Also the code specific to the town room is now in `rooms/TownRoom.hx`.

The spaghetti is gone.
